services:
  privy-cake-httpd:
    container_name: privy-cake-httpd
    working_dir: /app
    image: golang:alpine
    hostname: httpd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env 
    environment:
      - DATABASE_HOST=host.docker.internal
    command: sh -c "go run main.go"
    volumes:
      - ${PWD}:/app
    ports:
      - "8080:8080"
      - "8081:8081"