// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/teguh-satriya/privy-go/services"
)

// ListCakesService is an autogenerated mock type for the ListCakesService type
type ListCakesService struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx
func (_m *ListCakesService) Call(ctx context.Context) (*services.ListCakeResult, error) {
	ret := _m.Called(ctx)

	var r0 *services.ListCakeResult
	if rf, ok := ret.Get(0).(func(context.Context) *services.ListCakeResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListCakeResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewListCakesService interface {
	mock.TestingT
	Cleanup(func())
}

// NewListCakesService creates a new instance of ListCakesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewListCakesService(t mockConstructorTestingTNewListCakesService) *ListCakesService {
	mock := &ListCakesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
