// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	services "github.com/teguh-satriya/privy-go/services"
)

// UpdateCakesService is an autogenerated mock type for the UpdateCakesService type
type UpdateCakesService struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, params
func (_m *UpdateCakesService) Call(ctx context.Context, params *services.UpdateCakeParams) (*services.UpdateCakeResult, error) {
	ret := _m.Called(ctx, params)

	var r0 *services.UpdateCakeResult
	if rf, ok := ret.Get(0).(func(context.Context, *services.UpdateCakeParams) *services.UpdateCakeResult); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.UpdateCakeResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *services.UpdateCakeParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUpdateCakesService interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateCakesService creates a new instance of UpdateCakesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateCakesService(t mockConstructorTestingTNewUpdateCakesService) *UpdateCakesService {
	mock := &UpdateCakesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
